---
- name: Load OS-specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - main.yml
      paths:
        - 'vars'

- name: Ensure list of Packages is installed
  ansible.builtin.package:
    name:
    - podman
    - python3-cryptography
    state: {{ podman_package_state }}

- include_tasks: setup-quadlet.yaml
  when: podman_add_quadlet | bool

- include_tasks: setup-auto-update.yaml
  when: podman_add_auto_update | bool

- include_tasks: setup-prometheus.yaml
  when: podman_add_prometheus | bool