---
# auto update
- name: Ensure auto update timer directory is present
  ansible.builtin.file:
    path: "/etc/systemd/system/podman-auto-update.timer.d"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Ensure auto update timer file is present
  template:
    src: podman-auto-update-timer-override.conf.j2
    dest: "/etc/systemd/system/podman-auto-update.timer.d/podman-auto-update-timer-override.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    force: true
  notify: reload daemon

- meta: flush_handlers

- name: Ensure auto update is enabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: "{{ podman_systemd_scope }}"
  loop:
  - "podman-auto-update.timer"