---
# prometheus
- name: Ensure prometheus exporter is present
  template:
    src: podman-prometheus-exporter.container.j2
    dest: "{{ podman_quadlet_path }}/podman-prometheus-exporter.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    force: true
  notify: reload daemon

- meta: flush_handlers

- name: Ensure All Systemd Services are running
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: "{{ podman_systemd_scope }}"
  loop:
  - "podman.socket"
  - "podman-prometheus-exporter.service"
